name: 'Run dotenv-linter with reviewdog'
description: '🐶 Run dotenv-linter with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  dotenv_linter_flags:
    description: 'dotenv-linter flags. (dotenv-linter <dotenv_linter_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'dotenv-linter'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-code-suggestions].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: v0.13.0
        DOTENV_LINTER_VERSION: v3.1.1
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_DOTENV_LINTER_FLAGS: ${{ inputs.dotenv_linter_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
branding:
  icon: 'check-circle'
  color: 'green'
